### ISSUE TITLE
Correct this '|' to '||'.

### ISSUE THREAD

**Issue by gbrmate** [BME-MIT-IET/Zacskos-Leves-iet-2019#5]
**Testing/unittest/Dynamic/DynamicSubjectCollectionTTests.NetFull.cs, Line 108**

The use of non-short-circuit logic in a boolean context is likely a mistake - one that could cause serious program errors as conditions are evaluated under the wrong circumstances.

**Comment by Kecso-97** [comment]
Ha megbizonyosodunk róla, hogy a rövidzár tulajdonság nem okoz problémát, tényleg érdemes használni teljesítmény növelés céljából is.
